### ISSUE TITLE
Font size adjustment for the whole website

### ISSUE THREAD

**Issue by Asovrix** [stalkerg/anime-pictures#82]
Some older users might probably remember that at least 4 or 5 years ago the website had smaller fonts overall.
You can kinda see it here for example: https://web.archive.org/web/20140701115015/http://anime-pictures.net:80/
Font size increase probably happened because of adapting the site to mobile web browsers?
The thing is, I didn't like such huge text too much, so I've made myself a userstyle which roughly switches it back to how it was before:
```css
body,b,a.big_tag {font-size:10pt}
.title,.sidebar_block h2 {font-size:10pt !important}
h1 {font-size:16pt;line-height:16pt}
input,select,.tags li a:not(.big_tag) {font-size:9pt}
.post_content,.sidebar_block,#search_form,#message_form,ul.body li,#chat_users {font-size:10pt;line-height:14pt}
.post_content_avatar {min-height:145px}
.post_content .body {padding:5px 0 5px 5px}
.menu {font-size:9pt;line-height:32px}
.menu select {font-size:7pt}
.menu,.menu ul li,.menu ul li a {height:32px}
.menu ul li {padding:0 8px}
.icon_add_image,.icon_new_message,.icon_new_image,.icon_delete_big,.icon_edit_big {width:24px;height:24px}
.form_table .icon_delete_big,.form_table .icon_edit_big,.icon_delete,.icon_frame,.icon_edit,.icon_close,.icon_apply {height:16px;width:16px}
.subscribed_tags p {line-height:24px}
#chat_field tr td {padding:0 2px}
```

Would it be possible to have some kind of way of changing the font size on the site, either in the form of increasing/decreasing it directly with -/+ buttons placed somewhere on the site (header/footer/user settings) or as alternative versions of already existing styles?
